[package]
name = "nixon"
version = "0.1.0"
authors = ["msizanoen1 <qtmlabs@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.17.0"
tempfile = "3.1.0"
anyhow = "1.0.31"
structopt = "0.3.14"
